// lib/mockData.ts

export interface KpiDataItem {
  id: number;
  divisionId: number;
  divisionName: string;
  metricName: string;
  value: number;
  unit: string;
  periodMonth: number;
  periodYear: number;
  day: number; // kita pertahankan ini agar logika grouping nanti bisa pakai tanggal
}

// Contoh data dummy yang sudah dimodifikasi:
// (Tambahkan entri untuk bulan Mei dan Juli 2025, misalnya)
export const kpiData: KpiDataItem[] = [
  // --- Data Mei 2025 ---
  {
    id: 101,
    divisionId: 1,
    divisionName: "Keuangan & Akuntansi",
    metricName: "Jumlah Invoice Dibayar",
    value: 100,
    unit: "unit",
    periodMonth: 5,
    periodYear: 2025,
    day: 8,
  },
  {
    id: 102,
    divisionId: 2,
    divisionName: "Administrasi & Umum",
    metricName: "Jumlah Dokumen Diarsipkan",
    value: 180,
    unit: "unit",
    periodMonth: 5,
    periodYear: 2025,
    day: 12,
  },
  // … (Anda bisa menambah entri lain untuk melekat di Mei 2025)
  // --- Data Juni 2025 (existing) ---
  {
    id: 1,
    divisionId: 1,
    divisionName: "Keuangan & Akuntansi",
    metricName: "Jumlah Invoice Dibayar",
    value: 120,
    unit: "unit",
    periodMonth: 6,
    periodYear: 2025,
    day: 3,
  },
  {
    id: 2,
    divisionId: 1,
    divisionName: "Keuangan & Akuntansi",
    metricName: "Rata-rata Waktu Pembayaran",
    value: 2.8,
    unit: "hari",
    periodMonth: 6,
    periodYear: 2025,
    day: 10,
  },
  {
    id: 3,
    divisionId: 1,
    divisionName: "Keuangan & Akuntansi",
    metricName: "Persentase Invoice Tepat Waktu",
    value: 94,
    unit: "%",
    periodMonth: 6,
    periodYear: 2025,
    day: 17,
  },
  {
    id: 4,
    divisionId: 2,
    divisionName: "Administrasi & Umum",
    metricName: "Jumlah Dokumen Diarsipkan",
    value: 200,
    unit: "unit",
    periodMonth: 6,
    periodYear: 2025,
    day: 5,
  },
  {
    id: 5,
    divisionId: 2,
    divisionName: "Administrasi & Umum",
    metricName: "Rata-rata Waktu Proses Surat",
    value: 3.5,
    unit: "hari",
    periodMonth: 6,
    periodYear: 2025,
    day: 12,
  },
  {
    id: 6,
    divisionId: 3,
    divisionName: "Administrasi SDM",
    metricName: "Jumlah Karyawan Ditangani",
    value: 50,
    unit: "unit",
    periodMonth: 6,
    periodYear: 2025,
    day: 8,
  },
  {
    id: 7,
    divisionId: 3,
    divisionName: "Administrasi SDM",
    metricName: "Tingkat Absensi",
    value: 4.2,
    unit: "%",
    periodMonth: 6,
    periodYear: 2025,
    day: 18,
  },
  {
    id: 8,
    divisionId: 4,
    divisionName: "Administrasi Pengelolaan",
    metricName: "Jumlah Proyek Terlaksana",
    value: 8,
    unit: "unit",
    periodMonth: 6,
    periodYear: 2025,
    day: 2,
  },
  {
    id: 9,
    divisionId: 4,
    divisionName: "Administrasi Pengelolaan",
    metricName: "Persentase Proyek Selesai Tepat Waktu",
    value: 75,
    unit: "%",
    periodMonth: 6,
    periodYear: 2025,
    day: 22,
  },
  {
    id: 10,
    divisionId: 5,
    divisionName: "Pelaksana Pengelolaan",
    metricName: "Jumlah Tugas/Kegiatan",
    value: 120,
    unit: "unit",
    periodMonth: 6,
    periodYear: 2025,
    day: 1,
  },
  {
    id: 11,
    divisionId: 5,
    divisionName: "Pelaksana Pengelolaan",
    metricName: "Rata-rata Waktu Penyelesaian",
    value: 5.2,
    unit: "jam/hari",
    periodMonth: 6,
    periodYear: 2025,
    day: 15,
  },
  {
    id: 12,
    divisionId: 5,
    divisionName: "Pelaksana Pengelolaan",
    metricName: "Persentase Kegiatan Selesai",
    value: 88,
    unit: "%",
    periodMonth: 6,
    periodYear: 2025,
    day: 28,
  },
  // --- Data Juli 2025 ---
  {
    id: 201,
    divisionId: 1,
    divisionName: "Keuangan & Akuntansi",
    metricName: "Jumlah Invoice Dibayar",
    value: 140,
    unit: "unit",
    periodMonth: 7,
    periodYear: 2025,
    day: 6,
  },
  {
    id: 202,
    divisionId: 2,
    divisionName: "Administrasi & Umum",
    metricName: "Jumlah Dokumen Diarsipkan",
    value: 210,
    unit: "unit",
    periodMonth: 7,
    periodYear: 2025,
    day: 14,
  },
  {
    id: 203,
    divisionId: 3,
    divisionName: "Administrasi SDM",
    metricName: "Jumlah Karyawan Ditangani",
    value: 55,
    unit: "unit",
    periodMonth: 7,
    periodYear: 2025,
    day: 10,
  },
  // … (Anda bisa tambahkan entri lain untuk Juli 2025)
];
